{
 "title": "Public Connected Validators Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current connected validators",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validators_connected", "legendFormat": "{{NodeID}}" }
   ]
  },
  {
   "title": "Uptime of Blockdaemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-Lx7BqRD3LQuqZbpJzkc5UDTZb66cpez95\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Blockdaemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-DMAS3hKKWMydmWGmGd265EYCoV7zFWEHK\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Blockdaemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 24, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-2oZa4x84qqpdNqxKSL3PW28iex3VS1NQT\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Blockdaemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-4XZ7a7fGCzw6xqMFNQHy46JjUXnnq51Y1\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of In to the Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-LQHTbb1UKdB2mzWRoJWR6ZapvNmkZzWw\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of In to the Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 24, "y": 17 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-KrKGrfzP2orrkyiuacKABvyGGty3KffQw\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of In to the Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-6zMLLn4GvWRApEjAojJNgUEYHxfp2pbPi\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of In to the Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-8bPGGqcmhxL8M7LML5sVvfKRQGDn17uPU\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 24, "y": 25 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-6dBcEfrUMmhTbShvQfiqpybLmvUHtoFem\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-6LWYVCBLcUKW89GXSAscosCAxhyMeoGQR\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-2tpa7L26X8asp9Y5ZpRRtU61iPaooCQ9R\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 24, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-6FDUTBPEHQmf7S5838REhubwhfPAaJz1i\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Figment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-95G1AziLcVNUtBHSzc8naSR1bUVvkDEyR\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Figment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-Bd4G59NYc1zP9mMVf2yMzaSFA4StQuJn8\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Figment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 24, "y": 41 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-Lkwe2cpLYh3MwmbsDjuFkJ4ecx5CPxYNJ\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Figment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-HztJLzW4WwNYteuXpZ8cC9NnZ2cHD1X3Z\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Flare Foundation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-EQkfps4HcNP5PFmEG2h9QmBT3VsRu9kKu\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Flare Foundation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 24, "y": 49 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-4Y6Hxd42SjQ4GNJHYF9GFjKEu2KAYTPDo\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Flare Foundation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-5bTyYGC8rzxaQ9HFucqRM4aFwYGqT8ciA\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  },
  {
   "title": "Uptime of Flare Foundation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "avg_over_time(validators_connected{NodeID=\"NodeID-FDQmoefauig76jy7wac8kP5MHdLef9p9o\"}[1d])",
     "legendFormat": "{{NodeID}}"
    }
   ]
  }
 ]
}